spring.application.name=foodiesapi
#mongodb config
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Foodies
#spring.data.mongodb.uri=mongodb://localhost:27017/Foodies
logging.level.org.springframework.data.mongodb=DEBUG

#aws s3 config
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-south-1
aws.s3.bucketName=fodies-food

#secret key for jwt
mySuperSecretKey123456789012345678901234567890
jwt.secret.key=${JWT_SECRET}
#razorpay-data
razorpay_key= ${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}


